### ISSUE TITLE
SyntaxError: Unexpected token Issue

### ISSUE THREAD

**Issue by nvsajeeva** [neighbourhoodie/couch-continuum#71]
I installed the tool by running following commands on Ubuntu 1604

```
apt-get install npm
apt-get install nodejs-legacy 
apt-get install nodejs
npm install -g couch-continuum

```
But it gives the following error

`couch-continuum -h
/usr/local/lib/node_modules/couch-continuum/bin.js:13
function getContinuum ({
                       ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3`

**Comment by janl** [comment]
which nodes version is this

**Comment by nvsajeeva** [comment]
```
node -v
v4.2.6
```

**Comment by janl** [comment]
I think you need at least 8, 4 is very very old.

**Comment by nvsajeeva** [comment]
Thanks. It works with node v14.5.0

**Comment by janl** [comment]
great, I’ll leave this open so we can tighten up the required versions
