### ISSUE TITLE
"Expected values to be strictly equal" error while running Continuum

### ISSUE THREAD

**Issue by nvsajeeva** [neighbourhoodie/couch-continuum#72]
I get the following error while running the tool

`couch-continuum -N mydatabase -q 1 -n 3 -u http://user:password@localhost:5984`

```
Unexpected error. Please report this so we can fix it!
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

false !== true

    at CouchContinuum._isInUse (/usr/lib/node_modules/couch-continuum/index.js:314:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CouchContinuum.createReplica (/usr/lib/node_modules/couch-continuum/index.js:337:5)
    at async Object.handler (/usr/lib/node_modules/couch-continuum/bin.js:128:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: 'strictEqual'
}

```
Environment:
couchdb 2.3.0
Ubuntu 16.04
Node v14.5.0

**Comment by janl** [comment]
can you run with `-v`?

**Comment by jungalwala** [comment]
Jan, 

I am getting the same response.

Couchdb: 3.1.0
Debian 9
Node: 12.18.3

`couch-continuum -s database_name -q 16 -n 1 -v -u "http://YYYYY:XXXXXX@127.0.0.1:5984"
[couch-continuum] Created new continuum: {
  "filterTombstones": false,
  "interval": 1000,
  "n": 1,
  "q": 16,
  "replicateSecurity": true,
  "source": "127.0.0.1:5984/database_name"
  "target": "127.0.0.1:5984/temp_copy_database_name",
  "url": "127.0.0.1:5984"
}
[couch-continuum] Migrating database: 127.0.0.1:5984/database_name
[couch-continuum] Creating replica 127.0.0.1:5984/temp_copy_database_name...
[couch-continuum] [0/5] Checking if primary is in use...
Unexpected error. Please report this so we can fix it!
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
false !== true
    at CouchContinuum._isInUse (/usr/lib/node_modules/couch-continuum/index.js:314:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async CouchContinuum.createReplica (/usr/lib/node_modules/couch-continuum/index.js:337:5)
    at async Object.handler (/usr/lib/node_modules/couch-continuum/bin.js:128:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: 'strictEqual'
}`

**Comment by garbados** [comment]
It appears the issue occurs when trying to determine if the given database is still in use. The error traces to the function that determines whether a database is still in use, and I think it is being caused by replication tasks to unrelated databases. A fix is incoming...
